---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uams-consumer-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: jdcloud-lvm