apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: uams-am
    provider: uams
    version:  3.7.3
    group: cn.bjca.uams
  name: uams-am
  namespace: default
spec:
  serviceName: uams-am-service
  replicas: 1
  selector:
    matchLabels:
      app: uams-am
      provider: uams
      group: cn.bjca.uams
  template:
    metadata:
      labels:
        app: uams-am
        provider: uams
        version:  3.7.3
        group: cn.bjca.uams
    spec:
      volumes:
        - configMap:
            defaultMode: 256
            name: uams-config-mapping
            optional: false
          name: vol1
        - name: uams-am-logs
          persistentVolumeClaim:
            claimName: uams-am-logs
      containers:
        - args:
            - -c
            - sh /opt/uams/bin/start.sh
          command:
            - /bin/bash
          env:
            - name: MODULE_NAME
              value: am
            - name: runOnBackground
              value: "false"
            - name: applicationLogDir
              value: /root/logs/uams-am
            - name: applicationDir
              value: /app/uams-am
            - name: enableDataPersist
              value: "false"
            - name: enableUMP
              value: "false"
            - name: enableLogPersist
              value: "false"
            - name: umpBaseDir
              value: /var/log/footstone/metrics
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: tpaas.registry.hub/test/uams:3.7.3
          imagePullPolicy: Always
          name: uams-am
          ports:
            - containerPort: 18000
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/uams/logs
              name: uams-am-logs
            - mountPath: /opt/uams/config
              name: vol1

