apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.bjca.footstone/status: online
    app.kubernetes.io/env: DEV
    app.kubernetes.io/name: uams-opendj
  name: uams-opendj
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.bjca.footstone/status: online
      app.kubernetes.io/env: DEV
      app.kubernetes.io/name: uams-opendj
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.bjca.footstone/deploy-status: online
        app.bjca.footstone/status: online
        app.kubernetes.io/env: DEV
        app.kubernetes.io/name: uams-opendj
    spec:
      containers:
      - args:
        - -c
        - sh /opt/uams/bin/start.sh
        command:
        - /bin/bash
        env:
        - name: MODULE_NAME
          value: opendj
        - name: runOnBackground
          value: "false"
        - name: applicationLogDir
          value: /root/logs/uams-opendj
        - name: applicationDir
          value: /app/uams-opendj
        - name: enableDataPersist
          value: "false"
        - name: enableUMP
          value: "false"
        - name: enableLogPersist
          value: "false"
        - name: umpBaseDir
          value: /var/log/footstone/metrics
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: tpaas.registry.hub/test/uams:3.7.3
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - rm -rf /var/log/footstone/metrics/$MY_POD_NAME
        name: uams-opendj
        ports:
        - containerPort: 1389
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4000Mi
          requests:
            cpu: 10m
            memory: 1Gi
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/k8s/
          name: script-dir
        - mountPath: /opt/uams/config
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: script-dir
      - configMap:
          defaultMode: 256
          name: uams-config-mapping
          optional: false
        name: vol1
