apiVersion: v1
data:
  jvm.properties: |-    
    #支持的模块名,多个模块用半角空格分隔，开机自启动的模块也受该模块列表控制
    tomcatModules=am idm
    springbootModules=portal consumer radius

    #该文件定义了jvm相关的参数

    #该参数定义的为所有模块均需使用的jvm参数
    common=-Dfile.encoding=UTF-8 -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=@UAMS_HOME@/logs/@MODULE_NAME@-heapdump -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom -Dlogback.configurationFile=@UAMS_HOME@/config/logback.xml

    #该参数定义的是在未给模块指定jvm参数时所使用的默认参数，如为模块指定了则不会使用
    default=-Xms512m -Xmx1024m

    #以下为各模块特定的jvm参数，未指定参数的模块使用default定义的参数
    idm=-Xms2048m -Xmx2048m -Xss1024K
    portal=-Xms512m -Xmx2048m -Xss1024K -DCAT_ENABLED=false

    am=-Xms2048m -Xmx2048m -Xss1024K
  license.lic: PGxpY2Vuc2U+PHZlcnNpb24+MTwvdmVyc2lvbj48dGJzPjxzbj5DQjVFMzhBMy1GQTlFLTREMzktQjY3MS00MUVBMDg4MTNFRjc8L3NuPjxwcm9kdWN0bmFtZT5IQU9UWTwvcHJvZHVjdG5hbWU+PHByb2R1Y3R2ZXJzaW9uPjE8L3Byb2R1Y3R2ZXJzaW9uPjx0eXBlPkRFTU88L3R5cGU+PHN0YXJ0PjIwMjItMDItMTU8L3N0YXJ0PjxlbmQ+MjAyMi0wNS0xNTwvZW5kPjxod2luZm8+ZjhwQnEyeldSV001VUFLT09UbnhKOG8wZE44PTwvaHdpbmZvPjxwZXJtaXNzaW9uPmFwcGNvdW50PTEwMCx1c2VyY291bnQ9MTAwMDAwMDwvcGVybWlzc2lvbj48L3Ricz48c2lnbmF0dXJlPjxzaWduYWxnPlNIQTF3aXRoUlNBPC9zaWduYWxnPjxzaWdudmFsdWU+bnpHSUx4RTlNaTZkV2xvcHA2aVZpWnJRdVdvb0Z0STZFY2p2N1d2MU5yMlo4TW1jUzd2RkV2aE41NjU0SmFBbFBPRGNlRndEOWVIME04NGo3ZnF1YWZnZEsxUklqY04rem50OTJOM1hhSVZwOWdvWUVDT1M5amczNm8zWnVoRnhwMUZKK2s5RnFlK3ZkWUJ6SzZ4T3V4VFlQS1ZDRDFDSEQwVDlzenFvdHBjPTwvc2lnbnZhbHVlPjxzaWduY2VydD5NSUlGQURDQ0EraWdBd0lCQWdJS0d6QUFBQUFBQUZBOWpqQU5CZ2txaGtpRzl3MEJBUVVGQURCU01Rc3dDUVlEVlFRR0V3SkRUakVOTUFzR0ExVUVDZ3dFUWtwRFFURVlNQllHQTFVRUN3d1BVSFZpYkdsaklGUnlkWE4wSUVOQk1Sb3dHQVlEVlFRRERCRlFkV0pzYVdNZ1ZISjFjM1FnUTBFdE1UQWVGdzB4T1RBek1qY3hOakF3TURCYUZ3MHlNakExTVRreE5UVTVOVGxhTUZNeEN6QUpCZ05WQkFZVEFrTk9NUTB3Q3dZRFZRUUtEQVJDU2tOQk1SVXdFd1lEVlFRTERBem5vSlRsajVIa3VJRHBnNmd4SGpBY0JnTlZCQU1NRmVTNnArV1RnZWFPaU9hZGcrZXVvZWVRaHVXUm1EQ0JuekFOQmdrcWhraUc5dzBCQVFFRkFBT0JqUUF3Z1lrQ2dZRUF0OFlBdTJWM3NLVU5zc2d6alAzTlFvZFFtc2p1eUtqS25lMFRveEsrdW1Vd3ZEa2txQjZiM2JvNVBibHB3bWh4SjA5VjR6K25hVTVHemFVSDBmK05VeDZza2M0K2ozYVBHMVBQWi9hSGFRcEk2YXM2YnJXNzlPbEJCa3UyK1BYU2FEajVGTHArRExpUnpYWC9hcmw0SnorY2FwWjU1dnYyQ0lXNWFjNDNmVmtDQXdFQUFhT0NBbGt3Z2dKVk1COEdBMVVkSXdRWU1CYUFGS3c3N0s4TW8xQU83Nit2dEU5c085dlJWOUtKTUIwR0ExVWREZ1FXQkJTcTVXUVc0K09PNWk0RllXRVpGV0FCUEhpYkN6QUxCZ05WSFE4RUJBTUNCc0F3Z2E4R0ExVWRId1NCcHpDQnBEQnRvR3VnYWFSbk1HVXhDekFKQmdOVkJBWVRBa05PTVEwd0N3WURWUVFLREFSQ1NrTkJNUmd3RmdZRFZRUUxEQTlRZFdKc2FXTWdWSEoxYzNRZ1EwRXhHakFZQmdOVkJBTU1FVkIxWW14cFl5QlVjblZ6ZENCRFFTMHhNUkV3RHdZRFZRUURFd2hqWVROamNtd3lOekF6b0RHZ0w0WXRhSFIwY0RvdkwyeGtZWEF1WW1wallTNXZjbWN1WTI0dlkzSnNMM0IwWTJFdlkyRXpZM0pzTWpjdVkzSnNNQWtHQTFVZEV3UUNNQUF3RVFZSllJWklBWWI0UWdFQkJBUURBZ0QvTUIwR0JTcFdDd2NCQkJSVFJqRXlNREV3TkRFNU56VXhNakV4TmpNMU9EQWRCZ1VxVmdzSENBUVVVMFl4TWpBeE1EUXhPVGMxTVRJeE1UWXpOVGd3SUFZSVlJWklBWWI0UkFJRUZGTkdNVEl3TVRBME1UazNOVEV5TVRFMk16VTRNQnNHQ0NwV2hrZ0JnVEFCQkE4eE1ESXdPREF3TURJM09UZ3dNall3SlFZS0tvRWNodTh5QWdFRUFRUVhOa05BVTBZeE1qQXhNRFF4T1RjMU1USXhNVFl6TlRnd0tnWUxZSVpJQVdVREFnRXdDUW9FRzJoMGRIQTZMeTlpYW1OaExtOXlaeTVqYmk5aWFtTmhMbU55ZERBUEJnVXFWaFVCQVFRR01UQXdNREF3TUVBR0ExVWRJQVE1TURjd05RWUpLb0VjaHU4eUFnSUJNQ2d3SmdZSUt3WUJCUVVIQWdFV0dtaDBkSEE2THk5M2QzY3VZbXBqWVM1dmNtY3VZMjR2WTNCek1CTUdDaXFCSElidk1nSUJBUjRFQlF3RE5UTTJNQTBHQ1NxR1NJYjNEUUVCQlFVQUE0SUJBUUNoOTBjbllsWEp0bUVhL0hLWnBrdElmV2VhUHNZNGtwaHlkRzFyYWZybjB2WHBUZjhNaVMrK1FLRzQ3dVp2TFVsQzNHcGRibTdjTnN3aWFjKzJzV3lsQWZ5bW5UQm9Oc3RCMWNEaDl0NnUrSkFmeWFMdXg2aTJJaFZkU3JxTWdOZ1hQWXkzYjVhWXB2akY1MnRUL1J3em1qaVpXT2RnNjd3LzFQaTlsenhIUURDdVlmNTkxSHg3YjhYZCtDOTFTOVlFQVpzMmdOUVQ5QXZRajdDYUlLbk9HTHNDV3htclBrZVdCeVFZMDRJYTJTckxXU3RMYS9oOVRTa01BQ3d5S2w0bDM4QWtqTitNMGxkTi9pKzZHcXRNWmsyWmtwZmlDTFhVamRVMVBUWXl3aExJSUFyM1AzS2syc2U5Q1NlMnFIbTJVdG55U010REYvQUtzaTIzb2p1Nzwvc2lnbmNlcnQ+PC9zaWduYXR1cmU+PC9saWNlbnNlPg==
  logback.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<configuration scan=\"true\"
    scanPeriod=\"10 seconds\">\n\t<!-- 控制台 appender -->\n\t<appender name=\"STDOUT\"
    class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n\t\t<file>${UAMS_HOME}/logs/${MODULE_NAME}-console.log</file>\n\t\t<rollingPolicy
    class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n\t\t\t<!-- 按天回滚
    daily -->\n\t\t\t<!-- log.dir 在maven profile里配置 -->\n\t\t\t<fileNamePattern>${UAMS_HOME}/logs/history/${MODULE_NAME}-console-%d{yyyy-MM-dd}.log</fileNamePattern>\n\t\t\t<!--
    日志最大的历史 60天 -->\n\t\t\t<maxHistory>60</maxHistory>\n\t\t</rollingPolicy>\n\t\t<encoder>\n\t\t\t<pattern>%d{yyyy-MM-dd
    HH:mm:ss.SSS} [%thread] %-5level %logger[%line] - %msg%n</pattern>\n\t\t</encoder>\n\t</appender>\n
    \   \n\t<!-- 出错日志 appender  -->\n\t<appender name=\"ERROR\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n\t\t<file>${UAMS_HOME}/logs/${MODULE_NAME}-error.log</file>\n\t\t<rollingPolicy
    class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n\t\t\t<!-- 按天回滚
    daily -->\n\t\t\t<!-- log.dir 在maven profile里配置 -->\n\t\t\t<fileNamePattern>${UAMS_HOME}/logs/history/${MODULE_NAME}-error-%d{yyyy-MM-dd}.log</fileNamePattern>\n\t\t\t<!--
    日志最大的历史 60天 -->\n\t\t\t<maxHistory>60</maxHistory>\n\t\t</rollingPolicy>\n\t\t<encoder>\n\t\t\t<pattern>%d{yyyy-MM-dd
    HH:mm:ss.SSS} [%thread] %-5level %logger[%line] - %msg%n</pattern>\n\t\t</encoder>\n\t\t<filter
    class=\"ch.qos.logback.classic.filter.LevelFilter\"><!-- 只打印错误日志 -->\n\t\t\t<level>ERROR</level>\n\t\t\t<onMatch>ACCEPT</onMatch>\n\t\t\t<onMismatch>DENY</onMismatch>\n\t\t</filter>\n\t</appender>\n\n\t<!--
    info日志 appender  -->\n\t<appender name=\"INFO\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n\t\t<file>${UAMS_HOME}/logs/${MODULE_NAME}-info.log</file>\n\t\t<rollingPolicy
    class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n\t\t\t<!-- 按天回滚
    daily -->\n\t\t\t<fileNamePattern>${UAMS_HOME}/logs/history/${MODULE_NAME}-info-%d{yyyy-MM-dd}.log</fileNamePattern>\n\t\t\t<!--
    日志最大的历史 60天 -->\n\t\t\t<maxHistory>60</maxHistory>\n\t\t</rollingPolicy>\n\t\t<encoder>\n\t\t\t<pattern>%d{yyyy-MM-dd
    HH:mm:ss.SSS} [%thread] %-5level %logger[%line] - %msg%n</pattern>\n\t\t</encoder>\n\t\t<filter
    class=\"ch.qos.logback.classic.filter.LevelFilter\"><!-- 只打印错误日志 -->\n\t\t\t<level>INFO</level>\n\t\t\t<onMatch>ACCEPT</onMatch>\n\t\t\t<onMismatch>DENY</onMismatch>\n\t\t</filter>\n\t</appender>\n
    \   \n    <!-- 慢sql日志 appender  -->\n\t<appender name=\"slowsqlAppender\" class=\"ch.qos.logback.core.FileAppender\">\n\t\t<file>${UAMS_HOME}/logs/${MODULE_NAME}-slowsql.log</file>\n\t\t<encoder>\n\t\t\t<pattern>%d{yyyy-MM-dd
    HH:mm:ss.SSS} [%thread] %-5level %logger[%line] - %msg%n</pattern>\n\t\t</encoder>\n\t</appender>\n
    \   \n    <!--记录rest接口日志，仅影响idm -->\n    <appender name=\"request\" class=\"ch.qos.logback.core.rolling.RollingFileAppender\">\n\t\t<file>${LOG_DIR}/logs/idm-request.log</file>\n\t\t<rollingPolicy
    class=\"ch.qos.logback.core.rolling.TimeBasedRollingPolicy\">\n\t\t\t<!-- 按天回滚
    daily -->\n\t\t\t<fileNamePattern>${LOG_DIR}/logs/idm-request-%d{yyyy-MM-dd}.log</fileNamePattern>\n\t\t\t<!--
    日志最大的历史 60天 -->\n\t\t\t<maxHistory>60</maxHistory>\n\t\t</rollingPolicy>\n\t\t<encoder>\n\t\t\t<pattern>%d{HH:mm:ss.SSS}
    [%thread] %-5level %logger - %msg%n</pattern>\n\t\t</encoder>\n\t\t<filter class=\"ch.qos.logback.classic.filter.LevelFilter\">\n\t\t\t<level>INFO</level>\n\t\t\t<onMatch>ACCEPT</onMatch>\n\t\t\t<onMismatch>DENY</onMismatch>\n\t\t</filter>\n\t</appender>\n
    \   \n\t<!--记录rest接口日志，仅影响idm -->\n\t<logger name=\"idmRequest\" level=\"info\">\n\t\t<appender-ref
    ref=\"request\" />\n\t</logger>\n    \n    <!-- 慢sql日志 -->\n    <logger name=\"com.alibaba.druid.filter.stat.StatFilter\"
    level=\"info\" additivity=\"false\">\n        <appender-ref ref=\"slowsqlAppender\"
    />\n    </logger>\n\n\t<!-- 公共组件的日志级别 -->\n\t<logger name=\"cn.org.bjca.uams.component\"
    level=\"error\"/>\n\n\t<!--日志打印的包的范围，及分类日志文件存储 -->\n\t<logger name=\"cn.org.bjca\"
    level=\"debug\"/>\n\n\t<!-- openam的日志级别,默认情况下受am控制台里日志配置的控制，如am启动后再修改此配置也会相应的修改日志级别
    -->\n\t<logger name=\"org.forgerock.restlet\" level=\"debug\"/>\n\n\t<logger name=\"cn.org.bjca.filter.security\"
    level=\"error\"/>\n\t<logger name=\"cn.org.bjca.mq\" level=\"error\"/>\n\n\t<logger
    name=\"cn.org.bjca.DistributedHashTable\" level=\"error\"/>\n\n\t<!-- spring的日志级别
    -->\n\t<logger name=\"org.springframework.web\" level=\"error\"/>\n\n\t<!-- kafka日志级别
    -->\n\t<logger name=\"org.apache.kafka\" level=\"error\"/>\n\t<logger name=\"org.springframework.kafka\"
    level=\"error\"/>\n\n\t<logger name=\"redis.clients.jedis.JedisSentinelPool\"
    level=\"error\"/>\n\n\t<!--获取应用列表 -->\n\t<logger name=\"cn.org.bjca.rest.ApplicationResource\"
    level=\"error\"/>\n\n\t<logger name=\"org.restlet\" level=\"info\"/>\n\t<!--控制台打印资源加载信息-->\n\t<root
    level=\"error\">\n\t\t<appender-ref ref=\"STDOUT\" />\n\t\t<appender-ref ref=\"INFO\"
    />\n\t\t<appender-ref ref=\"ERROR\" />\n\t</root>\n</configuration>"
  setenv: |-
    #!/bin/bash

    #am管理员密码
    export AM_ADMIN_PWD=12345678
    #am用户库类型：openDJ/目录服务器 Database/数据库
    export USER_STORE_TYPE=Database

    export OPENDJ_IP=uams-opendj-service
    export OPENDJ_PORT=31389
    export OPENDJ_CN="cn=Directory Manager"
    export OPENDJ_PWD=bjca@123
    export OPENDJ_CONFIG_DN=dc=uconf,dc=com
    export OPENDJ_USER_DN=dc=uams,dc=com

    #数据库配置
    export DB_TYPE=mysql
    export DB_IP=172.16.122.49
    export DB_PORT=31895
    export DB_USER=admin
    export DB_PWD=admin
    export DB_NAME=idm

    #redis配置,支持单机、哨兵、集群三种方式
    #系统会优先查找哨兵配置，找不到则查找集群配置，
    #再找不到则采用单机配置
    export REDIS_IP=
    #redis服务器端口号
    export REDIS_PORT=
    #redis服务器密码
    export REDIS_PWD=1QAZzaq1
    export REDIS_DATABASE=0
    #redis主节点名字
    export REDIS_SENTINEL_MASTER=
    #redis哨兵地址列表格式：ip:port,ip:port
    export REDIS_SENTINEL_NODES=
    #redis集群地址列表格式：ip:port,ip:port
    export REDIS_CLUSTER_NODES=redis-3uefhdnce4ei-svc.redis-3uefhdnce4ei:6379
    #redis集群重定向的最大数量
    export REDIS_CLUSTER_MAXREDIRECTS=3

    #kafka服务器ip地址
    export KAFKA_IP=kafka-8h04rwtgva-kafka-bootstrap.kafka-8h04rwtgva.svc
    export KAFKA_PORT=9092

    #idm内网ip
    export IDM_SERVICE_IP=uams-idm-service
    export IDM_SERVICE_PORT=80
    #idm外网ip或域名，指的是浏览器地址栏中输入的ip或域名
    #如通过安装包自带的nginx部署了https则需要保持内网地址和端口号
    export IDM_PUBLIC_IP=192.169.226.16
    #idm外网端口号，指的是浏览器地址栏中输入的端口号，必须指定值
    export IDM_PUBLIC_PORT=30801

    #am服务内地址，如做了集群应该是反向代理的地址
    export AM_SERVICE_IP=uams-am-service
    #am服务的端口号，如做了集群应该是反向代理的端口号，必须指定值
    export AM_SERVICE_PORT=80
    #am外网地址
    #如通过安装包自带的nginx部署了https则需要保持内网地址和端口号
    export AM_PUBLIC_IP=192.169.226.40
    #am外网端口号
    export AM_PUBLIC_PORT=31008

    #portal服务外网ip和端口号，默认情况下和内网相同
    #如通过安装包自带的nginx部署了https则需要保持内网地址和端口号
    export PORTAL_PUBLIC_IP=192.169.226.16
    export PORTAL_PUBLIC_PORT=31802
    #portal的oauth2的回调地址
    export PORTAL_REDIRECT_URL=http://192.169.226.16:31802/portal/oauth2Callback

    #consumer服务ip
    export CONSUMER_SERVICE_IP=uams-consumer-service
    export CONSUMER_SERVICE_PORT=80
  sysconfig.properties: |-
    isInitSuccess=true
    userStoreType=${USER_STORE_TYPE}
    isStartValid=2013
    statisticsFlag=true
    mobilFlag=true
    openDjIp=${OPENDJ_IP}
    openDjPort=${OPENDJ_PORT}
    openDjCn=${OPENDJ_CN}
    openDjPwd=${OPENDJ_PWD}
    openDjUserDn=${OPENDJ_USER_DN}
    amUrl=http://${AM_SERVICE_IP}:${AM_SERVICE_PORT}/am
    amAdminPwd=${AM_ADMIN_PWD}

    portal.oauth2.redirectUrl=${PORTAL_REDIRECT_URL}
kind: ConfigMap
metadata:
  labels:
    cattle.io/creator: norman
  name: uams-config-mapping
  namespace: default
